### ISSUE TITLE
Add-On fails to activate if GitHub not reachable

### ISSUE THREAD

**Issue by AchimA** [AchimA/CAD-Helper#7]
```
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/AchimA/CAD-Helper/releases/latest (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001FB086C7820>, 'Connection to api.github.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "N:\EnDes\Blender\blender-4.0.0-beta+v40.1c4b2ad17f5f-windows.amd64-release\4.0\scripts\modules\addon_utils.py", line 341, in enable
    importlib.reload(mod)
  File "N:\EnDes\Blender\blender-4.0.0-beta+v40.1c4b2ad17f5f-windows.amd64-release\4.0\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\___user___\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\CAD-Helper\__init__.py", line 39, in <module>
    importlib.reload(
  File "N:\EnDes\Blender\blender-4.0.0-beta+v40.1c4b2ad17f5f-windows.amd64-release\4.0\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\___user___\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\CAD-Helper\ui.py", line 29, in <module>
    latest_version = check_addon_version()
  File "C:\Users\___user___\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\CAD-Helper\ui.py", line 25, in check_addon_version
    print(github_data['message'])
UnboundLocalError: local variable 'github_data' referenced before assignment
```

**→ remove the line:         #print(github_data['message'])**
```
def check_addon_version():
    # Fetch the latest version from GitHub
    try:
        response = requests.get('https://api.github.com/repos/AchimA/CAD-Helper/releases/latest')
        github_data = response.json()
        latest_version = github_data['tag_name']
    except:
        latest_version = None
        print('WARNING: failed to fetch GitHub version')
        #print(github_data['message'])
    return latest_version
```

**Comment by AchimA** [comment]
Solved in v0.4.1
